export default function Terms() {
  const colors = {
    cream: "#FAF7F0",
    navy: "#2A1F5A",
    purple: "#6244D9",
    purpleBorder: "rgba(98,68,217,0.25)",
    gray: "#6B6B80",
    grayLight: "#9990C5",
  };

  return (
    <div style={{ fontFamily: "system-ui, -apple-system, 'Helvetica Neue', sans-serif", background: colors.cream, color: colors.navy, lineHeight: 1.6 }}>

      {/* NAV */}
      <nav style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 48px", height: 68, borderBottom: `1px solid ${colors.purpleBorder}`, background: colors.cream, position: "sticky", top: 0, zIndex: 100 }}>
        <a href="/" style={{ textDecoration: "none", fontSize: 18, letterSpacing: "-0.3px" }}>
          <span style={{ fontWeight: 300, color: colors.navy }}>Code</span>
          <span style={{ fontWeight: 600, color: colors.purple }}>Whisper</span>
        </a>
        <a href="/" style={{ fontSize: 14, color: colors.gray, textDecoration: "none" }}>← Back to home</a>
      </nav>

      {/* CONTENT */}
      <main style={{ maxWidth: 720, margin: "0 auto", padding: "72px 48px 96px" }}>

        <p style={{ fontSize: 12, fontWeight: 600, letterSpacing: 4, color: colors.purple, textTransform: "uppercase", marginBottom: 16 }}>Legal</p>
        <h1 style={{ fontSize: "clamp(28px, 5vw, 44px)", fontWeight: 700, letterSpacing: -1, marginBottom: 12 }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: colors.grayLight, marginBottom: 56 }}>Last updated: April 23, 2026</p>

        {[
          {
            title: "Use of the app",
            body: "CodeWhisper is a coding practice tool for personal use only. You may not reverse engineer, resell, sublicense, or redistribute the app or any part of it.",
          },
          {
            title: "Free trial",
            body: "New accounts include a 7-day free trial with unlimited sessions. One trial per account. We reserve the right to end the trial period at any time with reasonable notice.",
          },
          {
            title: "Pro subscription",
            body: "Pro subscriptions are billed monthly. You may cancel at any time from your account settings. Upon cancellation, you retain access until the end of your current billing period. No partial refunds are issued for unused time.",
          },
          {
            title: "Lifetime license",
            body: "Lifetime licenses are a one-time purchase that grants access to the app and all future updates. Refunds are available within 7 days of purchase. After 7 days, all sales are final.",
          },
          {
            title: "Acceptable use",
            body: "You agree to use CodeWhisper only for lawful purposes. CodeWhisper is designed as a thinking aid — it guides your reasoning through Socratic hints and never provides direct answers. You may use it during technical interviews as a cognitive aid, similar to using documentation or notes, provided your interview format permits such tools. You are solely responsible for ensuring your use complies with the rules of any interview, assessment, or hiring process you participate in.",
          },
          {
            title: "Disclaimer",
            body: "CodeWhisper is an AI-powered tool and does not guarantee interview outcomes. Responses are generated by AI and may occasionally be inaccurate or incomplete. Use your own judgment when evaluating coaching responses.",
          },
          {
            title: "Limitation of liability",
            body: "To the maximum extent permitted by law, CodeWhisper shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app.",
          },
          {
            title: "Changes to terms",
            body: "We may update these terms from time to time. Continued use of the app after changes constitutes acceptance of the updated terms. We will notify users of significant changes via email.",
          },
          {
            title: "Governing law",
            body: "These terms are governed by the laws of the State of California, without regard to conflict of law principles.",
          },
          {
            title: "Contact",
            body: "Questions about these terms? Email us at hello@codewhisper-ai.com",
          },
        ].map((section) => (
          <div key={section.title} style={{ marginBottom: 40, paddingBottom: 40, borderBottom: `1px solid ${colors.purpleBorder}` }}>
            <h2 style={{ fontSize: 20, fontWeight: 600, color: colors.navy, marginBottom: 14 }}>{section.title}</h2>
            <p style={{ fontSize: 15, color: colors.gray, lineHeight: 1.8 }}>
              {section.title === "Contact"
                ? <>{section.body.replace("hello@codewhisper-ai.com", "")} <a href="mailto:hello@codewhisper-ai.com" style={{ color: colors.purple, textDecoration: "none" }}>hello@codewhisper-ai.com</a></>
                : section.body}
            </p>
          </div>
        ))}

      </main>

      {/* FOOTER */}
      <footer style={{ background: colors.cream, borderTop: `1px solid ${colors.purpleBorder}`, padding: "32px 48px", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 12 }}>
        <p style={{ fontSize: 13, color: colors.gray }}>© 2026 CodeWhisper. All rights reserved.</p>
        <div style={{ display: "flex", gap: 20, alignItems: "center" }}>
          <a href="mailto:hello@codewhisper-ai.com" style={{ color: colors.gray, textDecoration: "none", fontSize: 13 }}>hello@codewhisper-ai.com</a>
          <a href="/privacy" style={{ color: colors.gray, textDecoration: "none", fontSize: 13 }}>Privacy Policy</a>
          <a href="/terms" style={{ color: colors.gray, textDecoration: "none", fontSize: 13 }}>Terms of Service</a>
        </div>
      </footer>

    </div>
  );
}
